### ISSUE TITLE
Rasperry PI 4 - Lazarus Compile Error

### ISSUE THREAD

**Issue by CptnRoughnight** [Kagamma/evil-script#2]
System: Rasperry Pi 400

OS: Raspberry Pi OS 64bit

IDE/Compiler : Lazarus 2.2.6+dfsg2-2  / fpc 3.2.2+dfsg-20

Error : "Internal error 2014122220"
debugger points at : ScriptEngine.pas line 2767 - procedure AssignLocalInt(...)
`asm
      b P
end
`

hint : If I comment this section it will compile, but don't know the effects of it.

**Comment by Kagamma** [comment]
You can try to disable `SE_COMPUTED_GOTO` symbol. Free Pascal's aarch64 inline assembly feature is not mature enough and may cause issue like what you are seeing.

If you want to understand what this section of code does, see https://eli.thegreenplace.net/2012/07/12/computed-goto-for-efficient-dispatch-tables

**Comment by Kagamma** [comment]
I made a few changes, so now SE_COMPUTED_GOTO is automatically disabled if the lib is compiled for Aarch64 platform.

**Comment by CptnRoughnight** [comment]
> I made a few changes, so now SE_COMPUTED_GOTO is automatically disabled if the lib is compiled for Aarch64 platform.

Thanks for the effort! It works so far! :)
